name = "mcp-gis-ph"
main = "src/index.ts"
compatibility_date = "2025-01-01"
compatibility_flags = ["nodejs_compat"]

routes = [
  { pattern = "mcp.gis.ph", custom_domain = true }
]

[durable_objects]
bindings = []

[[migrations]]
tag = "v2"
deleted_classes = ["GisPhMCP"]